name: Build-Debug

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-dotnet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Cysharp/Actions/.github/actions/setup-dotnet@main
        with:
          dotnet-version: |
            3.1.x
            5.0.x
            6.0.x
      - run: dotnet build -c Debug
      - run: dotnet test -c Debug --no-build
